apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  CORS_ALLOWED_ORIGIN: {{ .Values.config.corsAllowedOrigins | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.dbHost | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.dbUser | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.config.dbPassword | quote }}
